// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfsvWL0sdw2YRVNb5PraxQOW19TSeGkc',
    appId: '1:424242613213:web:62d5799f29917074374434',
    messagingSenderId: '424242613213',
    projectId: 'bingr-12',
    authDomain: 'bingr-12.firebaseapp.com',
    storageBucket: 'bingr-12.firebasestorage.app',
    measurementId: 'G-TRJHKRTJBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtc6FOfv_bG-fsaIauvH4dDqew-1p9l3I',
    appId: '1:424242613213:android:ee0b58288613e632374434',
    messagingSenderId: '424242613213',
    projectId: 'bingr-12',
    storageBucket: 'bingr-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5O7N5ObOGHINpszIGpoHGmhskFDhKDXw',
    appId: '1:424242613213:ios:d84d0f48d20023f5374434',
    messagingSenderId: '424242613213',
    projectId: 'bingr-12',
    storageBucket: 'bingr-12.firebasestorage.app',
    iosBundleId: 'com.example.bingr',
  );
}
